name: Build, Lint, Test and Deploy

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-lint-test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
    outputs:
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true
      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ steps.packageExtension.outputs.vsixPath }}

  publish:
    name: Publish Github Action
    needs:
      - build-lint-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest
      - name: Publish
        if: success() && matrix.os == 'ubuntu-latest'
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}